# Generated by Django 2.2.2 on 2019-06-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Book Name', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
            ],
        ),
    ]
