# Generated by Django 2.2.2 on 2019-06-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='status',
            field=models.CharField(default=0, help_text='y for yes n for no', max_length=1),
        ),
    ]
